play-travis
Otus-DevOps-2018-11/inetman28_infra pull request #1
Opened 2018-12-25 09:34 UTC by inetman28

2018-12-29 13:36 UTC, mrgreyves requested changes
Здравствуйте! Необходимо заполнить пуллреквест. Спасибо!)

2019-01-02 11:20 UTC, inetman28 reviewed
Здравствуйте.

Лабораторная работа #4 выполнена. 
Нужно смержить play-travis с master branch.

2019-01-02 11:23 UTC, inetman28 reviewed
Здравствуйте. Лабораторная работа №4 выполнена.

2019-01-02 15:18 UTC, mrgreyves approved these changes
Здравствуйте! В следующий дз в описании пуллреквестов вы можете кратко описывать что именно было сделано. ДЗ принимаю!)

2019-01-02 16:21 UTC, merged